add contact-form
nyz83/microverse-portfolio pull request #4
Opened 2023-10-03 14:35 UTC by nyz83

# Pull Request: Project Miles Stone - Contact Form and Mobile Version
## Description 
This pull request includes the implementation of contact form and completing the mobile version.
## Changes Made
- Implemented the contact form with the following specifications:
  - Name field accepts up to 30 characters.
  - Email field accepts only valid email address.
  - Message field accepts up to 500 characters.
  - Added placeholder text for all the inputs fields.
  - Implemented form validation with HTML to prevent the empty submission.
  - Integrated FormSpree service to collect form data.
  - Used flexbox layout as per project guidelines.
  - Implemented button interactions
  - Ensured that design stay close to provided figma design as mush as possible.
## Code Review Request
I kindly request your review of the code changes made in this pull request. Your feedback is highly appreciated.

2023-10-04 10:38 UTC, HtetWaiYan7191 requested changes
Hi @nyz83  , 

![](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)


Good job so far! 👍 💯 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights

Nice Design :heavy_check_mark: 
Correct Git Flow :heavy_check_mark: 
Descriptive Pr :heavy_check_mark: 

## Required Changes ♻️


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-04 10:38 UTC, HtetWaiYan7191 commented on index.html
> +            <button class="contact__form--button | capitalize" type="button">get in touch</button>
Kindly consider to change the button type to `type="submit"` so that the button will trigger the form submission process and client side validation  😁

2023-10-07 17:06 UTC, nyz83 commented
@HtetWaiYan7191  Sir, I have added a final finishing touch for this week.

2023-10-08 05:11 UTC, HtetWaiYan7191 commented
Thanks for your patience @nyz83 😁 . I just checked your code and it's working fine 💯 . Great Job ! 💯 . Next time, after you have finished making changes, could you please move this card to the 'To Review' column and assign it to me again so that I can receive a notification from the Trello app? 😁

2023-10-08 05:13 UTC, HtetWaiYan7191 approved these changes
Hi @nyz83  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
![](https://media.giphy.com/media/3o72FcJmLzIdYJdmDe/giphy.gif)
## Highlights
- Descriptive PR ✔️
- Well Structured Code ✔️
- Correct Git flow ✔️
- Form works fine ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-08 06:35 UTC, merged